#!/usr/bin/env bash
#
# Populate a deterministic crawl fixture under $TEST_ROOT (default: <repo>/test).
# Intended workflow:
#   ./test_setup.sh
#   ./test.sh "$(pwd)/test"          # FS ↔ ecrawl ↔ ereport correlation (slow if tree is huge)
# Or: ./test_full.sh                # runs setup then test.sh in one shot
#
# Environment (optional):
#   TEST_ROOT   output directory (default: directory containing this script + /test)
#   DEPTH       depth of one long path under .../deep/ (default: 14)
#   BRANCHES    number of sibling dirs under .../wide/ (default: 5)
#   FILES_WIDE  regular files per wide branch (default: 4)

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TEST_ROOT="${TEST_ROOT:-$SCRIPT_DIR/test}"
DEPTH="${DEPTH:-14}"
BRANCHES="${BRANCHES:-5}"
FILES_WIDE="${FILES_WIDE:-4}"

log() { printf '[test_setup] %s\n' "$*"; }

rm_rf_tree() {
    if [[ -e "$TEST_ROOT" ]]; then
        log "removing existing $TEST_ROOT"
        rm -rf "$TEST_ROOT"
    fi
}

summarize() {
    local nd nf nl
    nd=$(find "$TEST_ROOT" -type d 2>/dev/null | wc -l | tr -d ' ')
    nf=$(find "$TEST_ROOT" -type f 2>/dev/null | wc -l | tr -d ' ')
    nl=$(find "$TEST_ROOT" -type l 2>/dev/null | wc -l | tr -d ' ')
    printf '\nSummary (find): dirs=%s files=%s symlinks=%s root=%s\n' "$nd" "$nf" "$nl" "$TEST_ROOT"
}

rm_rf_tree
mkdir -p "$TEST_ROOT"

log "creating deep chain (DEPTH=$DEPTH)"
p="$TEST_ROOT/deep"
mkdir -p "$p"
for ((i = 1; i <= DEPTH; i++)); do
    p="$p/seg$(printf '%03d' "$i")"
    mkdir -p "$p"
    printf 'depth marker seg %s\n' "$i" >"$p/README.txt"
done
printf 'leaf-data\n' >"$p/leaf_a.bin"
printf 'leaf-data\n' >"$p/leaf_b.bin"

log "creating wide subtree (BRANCHES=$BRANCHES FILES_WIDE=$FILES_WIDE)"
mkdir -p "$TEST_ROOT/wide"
for ((b = 0; b < BRANCHES; b++)); do
    mkdir -p "$TEST_ROOT/wide/b$(printf '%02d' "$b")/nested"
    for ((f = 0; f < FILES_WIDE; f++)); do
        printf 'wide branch %s file %s\n' "$b" "$f" >"$TEST_ROOT/wide/b$(printf '%02d' "$b")/f_${f}.txt"
    done
    printf 'nested\n' >"$TEST_ROOT/wide/b$(printf '%02d' "$b")/nested/inner.txt"
done

log "flat files at tree root"
touch "$TEST_ROOT/root_empty.dat"
printf 'hello\n' >"$TEST_ROOT/root_small.txt"

log "symlink + hardlink samples"
ln -sf "wide/b00/f_0.txt" "$TEST_ROOT/link_to_wide_file"
ln -f "$TEST_ROOT/root_small.txt" "$TEST_ROOT/hardlink_same_as_root_small"

log "other entry types (optional)"
mkdir -p "$TEST_ROOT/empty_dir"

printf '%s\n' \
    "This tree is generated by test_setup.sh (DEPTH=$DEPTH BRANCHES=$BRANCHES)." \
    "Run: ./test_full.sh   OR   ./test.sh \"$TEST_ROOT\"" \
    >"$TEST_ROOT/HOWTO.txt"

summarize
log "done."
